apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudsql-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudsql-proxy
  template:
    metadata:
      labels:
        app: cloudsql-proxy
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:latest
          command: ["/cloud_sql_proxy", "-dir=/cloudsql", "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
          resources:
            requests:
              memory: "256Mi"  # Request for memory
              cpu: "250m"      # Request for CPU
            limits:
              memory: "512Mi"  # Limit for memory
              cpu: "500m"      # Limit for CPU
      volumes:
        - name: cloudsql-credentials
          secret:
            secretName: cloudsql-instance-credentials
