apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy-internal-api-2
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services/proxy"]
    resourceNames: ["internal-api-service-2:80"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-internal-api-2-testadmin
  namespace: default
subjects:
  - kind: User
    name: "https://keycloak.neeranuchj.org/realms/kubernetes-zerotrust#testadmin"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: proxy-internal-api-2
  apiGroup: rbac.authorization.k8s.io