apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy-internal-api-1
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services/proxy"]
    resourceNames: ["internal-api-service-1:80"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-internal-api-1-access
  namespace: default
subjects:
  - kind: Group
    name: "user"                
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: "admin"             
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: proxy-internal-api-1     
  apiGroup: rbac.authorization.k8s.io

# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: proxy-all-services
#   namespace: default
# rules:
#   - apiGroups: [""]
#     resources: ["services/proxy"]
#     verbs: ["get"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: proxy-any-identity
#   namespace: default
# subjects:
#   - kind: User
#     name: "https://keycloak.neeranuchj.org/realms/kubernetes-zerotrust#testuser"
#     apiGroup: rbac.authorization.k8s.io
# roleRef:
#   kind: Role
#   name: proxy-all-services
#   apiGroup: rbac.authorization.k8s.io

