apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: external-cluster
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_CLUSTER_ID: external-cluster
  values:
    global:
      multiCluster:
        clusterName: external-cluster
      network: external-network
      meshID: mesh1
    cni:
      cniBinDir: /home/kubernetes/bin
      cniConfDir: /etc/cni/net.d
      excludeNamespaces:
        - istio-system
        - kube-system
  components:
    cni:
      enabled: true
