apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: NodePort   # Change this to NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080   # You can specify a port (e.g., 30080), or Kubernetes will allocate one automatically
  selector:
    istio: ingressgateway