apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-api-service-2
  labels:
    app: internal-api-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-api-service-2
  template:
    metadata:
      labels:
        app: internal-api-service-2
    spec:
      containers:
      - name: internal-api-service-2
        image: neeranuchj/internal-api-service-2:latest
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "250Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: internal-api-service-2
spec:
  selector:
    app: internal-api-service-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP
