version: '3'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  k6:
    image: grafana/k6
    volumes:
      - .:/scripts
    depends_on:
      - influxdb
    entrypoint: >
      k6 run --out influxdb=http://influxdb:8086/k6 /scripts/load-test.js

volumes:
  influxdb-data:
