apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: internal-api-2-vs
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /api/report
    route:
    - destination:
        host: internal-api-service-2.default.svc.cluster.local
        port:
          number: 80
